export const GET_TRENDING_BILLBOARD = 'GET_TRENDING_BILLBOARD';
export const GET_BOOKS = 'GET_BOOKS';
export const GET_SECTIONS = 'GET_SECTIONS';

export const GET_BOOK_CONTENT = 'GET_BOOK_CONTENT';

export const GET_READING_LIST = 'GET_READING_LIST';

export const SEARCH_BOOK_SUCCEED = 'SEARCH_BOOK_SUCCEED';
export const SEARCH_BOOK_FAILED = 'SEARCH_BOOK_FAILED';

export const FETCH_USER_LIBRARY_SUCCEED = 'FETCH_USER_LIBRARY_SUCCEED';
export const FETCH_USER_LIBRARY_FAILED = 'FETCH_USER_LIBRARY_FAILED';

export const FETCH_USER_LIKE_BOOKS_SUCCEED = 'FETCH_USER_LIKE_BOOKS_SUCCEED';
export const FETCH_USER_LIKE_BOOKS_FAILED = 'FETCH_USER_LIKE_BOOKS_FAILED';

export const START_NEW_BOOK_LOADING = 'START_NEW_BOOK_LOADING';
export const START_NEW_BOOK = 'START_NEW_BOOK_SUCCEED';
export const START_NEW_BOOK_FAILED = 'START_NEW_BOOK_FAILED';
export const FETCH_USER_BOOKS = 'FETCH_USER_BOOKS';
export const UPDATE_USER_BOOKS = 'UPDATE_USER_BOOKS';

export const SAVE_WORK = 'SAVE_WORK';
export const LOAD_WORK = 'LOAD_WORK';

export const PUBLISH_BOOK = 'PUBLISH_BOOK';
export const PUBLISH_BOOK_FAILED = 'PUBLISH_BOOK_FAILED';
