export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const GET_CART_ITEM = 'GET_CART_ITEM';
export const REMOVE_ALL_CART_ITEM = 'REMOVE_ALL_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
